import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [  // Changed from 'docs' to 'tutorialSidebar'
    {
      type: 'category',
      label: 'Chapter 1: Introduction',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'chapter-1' }],
    },
    {
      type: 'category',
      label: 'Chapter 2: Physical AI Modules',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'chapter-2' }],
    },
    {
      type: 'category',
      label: 'Chapter 3: Why Physical AI Matters',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'chapter-3' }],
    },
    {
      type: 'category',
      label: 'Chapter 4: Hardware Requirements',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'chapter-4' }],
    },
    {
      type: 'category',
      label: 'Chapter 5: Final Preparation',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'chapter-5' }],
    },
  ],
};

export default sidebars;